eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
logging:
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      product-service:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException

X-Internal-Gateway: inventory-gateway
